DEPARMENT <- list('laboratorio', 'laboratories', 'laboratory', 'laboratoire', 'institute', 'academic', 'department', 'division', 'faculty of ', 'genomics center', 'research station')

INSTITUTE <- list('college', 'university', 'universitat', 'universite',
                  'unversiteit', 'universita', 'universidad', 'universiti', 'hospital', 'hopitaux de', 'unidade de',
                  "ha'pital", 'istituti', 'istituto', 'institucio', 'institut', 'medical center', ' pharma',
                  'riuniti', 'clinic', ' school of medicine', 'karolinska sjukhuset',
                  'national institutes of health', 'cancer center', 'bioscience institute',
                  'national institute for', 'national center for ', 'national centre for',
                  'unilever research', 'national cardiovascular center',
                  'centro operativo', 'animal research centre', 'nutrition research center',
                  'national perinatal epidemiology unit', 'tanabe seiyaku', 'animal health trust',
                  'marine biological laboratory', ' medical school', ' research laboratories',
                  'baxter diagnostics', 'inserm', 'sylvius laboratory', 'broad institute', ' inra', '/inra',
                  'health chemical laboratory', 'genecor, inc', 'infirmary',
                  'national center for health', 'john innes centre', 'chru de la timone',
                  'chu de bordeaux', 'ecole nationale ', 'cape technologies',
                  'national chemical laboratory', ' national laboratory', 'department of research and development',
                  'academy of sciences', 'centre chirurgical de la porte', 'international centre of ',
                  'lawrence berkeley laboratory', 'albert einstein college', 'gedeon richter ltd',
                  ' nih', 'ufrgs', 'national research centre', ' co.', ' ltd.', ' ltd', 'inc.', 'research limited',
                  'clinic college of', 'center for', 'research center', 'research centre',
                  'schon klinik', 'innovaderm research', 'novartis', 'aquarium', 'foundation',
                  'permanente', 'healthcare system', 'national oncology institute',
                  'global research and development', 'health service', 'national primate research center',
                  'faculdade de ', ' urmc', ' pllc', ' pgimer', 'center for disease control',
                  'london school of ', 'ggze', 'health service executive', 'council for scientific',
                  'cnrs', 'eth zurich', 'johns hopkins', 'isconova', 'barts health', 'ceinge',
                  'national jewish health', 'german institute', 'iqwig', 'federal joint committee',
                  'nationale contre', 'cura villa maria', 'centre de psychologie', 'centro diagnostico',
                  'international reference centre', 'complesso integrato', 'health care centre',
                  'idiphim', 'cytogenetic laboratory', 'fondazione', 'facebook', 'google', 'association for',
                  ' llc', 'national museum', 'national research council', 'rehabilitation center',
                  'rehabilitation institute', 'oncology center', 'cancer centre', 'virginia tech',
                  'ciberesp', 'department of food', 'rothamsted research', 'evangelisches',
                  'ziekenhuizen', 'academy of ', 'chinese national ', 'pathology associates',
                  'science magnet', 'ucla ', ' ucsd', 'uc berkeley', 'uc san diego', 'trial group',
                  'acdi', 'specialty center', 'agemetra', 'national research institute', 'diabetes center',
                  'rothamsted research', 'affichem', 'disease association', 'ministry of health',
                  'incorporation', 'medical research council', 'develogen', 'innovation campus',
                  'flemish government', "centre d'etudes", 'kaist', 'epfl', ' eth', 'ecole normale',
                  'ecole polytechnique', 'mental health center', 'charite centrum', 'phc affairs',
                  'afmc', 'cdsr', 'chu de ', 'harvard school', 'karnavati school', 'academic centre for',
                  'school of public health', 'school of sport sciences', 'medical center', 'medical centre',
                  'neocodex', 'umc utrecht', 'centers for disease', 'cardiac surgery center',
                  'medical city', 'wisconsin department', "doctor's data", 'drug development office',
                  'research unit', 'ecogen', 'international corporation', 'tourism agency',
                  'naval research laboratory', 'infection research', 'health solutions',
                  'us military', 'us department', 'human genome center', 'siemens', 'swiss institute',
                  'usda', 'marine science center', 'u.s. geological', 'u.s. positive', 'u.s. Department',
                  'botanical center', 'municipal centre', 'municipal health', 'research council',
                  'national serology', 'national sexually', "d'aragona", 'metropolitan health',
                  'rosa and company', 'laboratory of oncology', 'oncology r&d', 'assessment service',
                  'cancer registry', 'technology agency', 'district health', 'irccs', 'pharmexa',
                  'scientific service', 'limited company', 'health authority', 'biodiversity center',
                  'national park', 'corporation', 'ucl ', 'escola nacional', 'va health system',
                  'agri-food', 'agrotech', 'agroforestry', 'umr micalis', 'allan rosenfield',
                  'allan wilson', 'allen institute', 'ameripath', 'biotechnologies', 'anaerobe systems',
                  'nhs trust')

REMOVE_INSTITUE <- list('pharmacology', 'college of pharmacy', 'institute of zoology', 'institute of population', 'institute of bioinformatics',
                        'institute of plant',  'section for ', 'institute of clinical medicine', 'department of clinical')

COUNTRY <- list(
  c('italy', 'italia', 'torino', 'turin', 'portici', 'palermo'),
  c('united kingdom', 'u.k.', '\buk\b', 'uk.', 'england', ' uk', 'liverpool','london', 'crumpsall', 'leicester', 'manchester', 'cardiff', 'salford','bradford', 'oxford', 'clwyd', 'edinburgh', 'edinburge'),
  c('united states of america', ' usa','u.s.a', 'u. s. a.', 'united states', 'massachusetts',
    'boston', 'howard university', 'torrance', 'san francisco', 'duarte', 'los alamos',
    'houston'),
  c('germany', 'frg', 'brd', 'f.r.g.', 'deutschland', 'engelskirchen', 'berlin',
    'hannover', 'marburg', 'mainz', 'leipzig', 'frankfurt','munich','magdeburg'),
  c('japan', 'keio University', 'jikei university', 'shiga university', 'jikei university',
    'niigata university', 'sendai city', 'shiba', 'asahikawa',
    'tokyo', 'yokohama', 'osaka', 'nagoya', 'sapporo', 'kobe', 'kyoto',
    'fukuoka', 'kawasaki', 'saitama', 'hiroshima', 'sendai', 'kitakyushu',
    'chiba', 'sakai', 'hamamatsu', 'niigata', 'shizuoka', 'okayama', 'asahikawa',
    'yamaguchi', 'okayama', 'gunma', 'hyogo', 'kanazawa', 'fukui', 'tajimi',
    'komagome', 'akita', 'suita', 'kochi', 'nara medical', 'keio', 'kobe university',
    'gunma', 'gifu university', 'toranomon', 'bunkyo gakuin','tokai university'),
  c('south korea', 'korea', 'seoul'),
  c('russia', 'moscow', "st. petersburg"),
  c('austria', 'linz', 'wien', ' graz', 'innsbruck'),
  c('israel', 'jerusalem', 'haifa', 'tel aviv'),
  c('norway', ' oslo'),
  c('finland', 'helsinki'),
  c('south africa', 'johannesburg'),
  c('france', 'paris', 'marseille', 'brest', 'limoges', 'toulouse'),
  c('canada', 'vancouver', 'ontario', 'ottawa', 'nova scotia', 'calgary', 'alberta'),
  c('denmark', 'copenhagen'),
  c('taiwan', 'taiwan, ', 'taipei', 'chi-mei medical'),
  c('china', 'beijing', 'pr china', 'hangzhou', 'zhejiang', 'shenyang', 'shanghai'),
  c('egypt', 'cairo'),
  c('poland', 'gdansk', 'krakow'),
  c('turkey', 'istanbul', ' ankara'),
  c('netherlands', 'utrecht', 'nijmegen', 'amsterdam', 'leiden'),
  c('belgium', 'belgique', ' namur', 'bruxelles', ' genk'),
  c('sweden', 'karlstad', 'uppsala', 'stockholm'),
  c('australia', ' perth', 'queensland', 'canberra', 'melbourne'),
  c('south africa', 'johannesburg', 'onderstepoort', 'pretoria'),
  c('hungary', 'ungarn'),
  c(' india', 'chandigarh', 'hyderabad', 'delhi', 'calcutta', 'wardha', ' ucms','ludhiana', 'vellore'),
  c('ireland', 'dublin', 'belfast'),
  c('colombia', 'bogota'),
  c('spain', ' madrid', ' toledo', ' alicante', 'zaragoza', 'saragossa', 'barcelona','hospital vega baja', 'valencia', 'malaga'),
  c('greece', 'athens'),
  c('new zealand', 'upper hutt', 'auckland'),
  c('saudi arabia', 'riyadh'),
  c('nigeria', 'ibadan'),
  c('croatia', 'yugoslavia', 'belgrade'),
  c('switzerland', 'basel', ' geneva', 'berne', 'zurich'),
  c('brazil', 'rio de janeiro'),
  c('thailand', 'bangkok'),
  c('argentina', 'buenos aires'),
  c('tunisia', 'tunis', 'tunisie'),
  c('czech republic', ' praha', 'prague', 'czechoslovakia'),
  c('hungary', 'budapest'),
  c('zimbabwe', 'bulawayo'),
  c('malaysia', 'kelantan'),
  c('vietnam', 'hanoi'),
  c('hong kong', 'hong kong'),
  c(' iran', 'tehran', 'shiraz', 'mashhad'),
  c('brazil', 'brasil', 'rio de janeiro', 'cordeiropolis'),
  c('mexico', 'mexico city'),
  c ('romania', 'bucharest'),
  c ('congo', 'democratic republic of congo'),
  c('armenia', 'yerevan'),
  c('bosnia and herzegovina', 'bosnia', 'herzegovina'),
  c('albania', 'tirana'),
  c('tanzania', 'morogoro'),
  c('sri lanka', 'sri lanka'),
  c('cyprus', 'nicosia'),
  c('gambia', ' banjul'),
  c('lithuania', 'lietuvos'),
  c ('peru', ' lima'),
  c('portugal', 'lisboa'),
  c('philippines', 'manila'),
  c('kuwait', 'kuwait city'),
  c('singapore')
)

STATES <- list('Alabama', 'Alaska', 'Arizona', 'Arkansas',
               'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida',
               'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
               'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
               'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
               'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
               'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
               'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
               'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
               'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Washington DC',
               ' AL', ' AK', ' AZ', ' AR', ' CA', ' CO', ' CT', ' DE', ' FL', ' GA ', ' GA,', ' HI',
               ' ID', ' IL', ' IN', ' IA', ' KS', ' KY', ' LA', ' ME', ' MD', ' MA,', ' MA ', ' MI',
               ' MN', ' MS', ' MO', ' MT', ' NE', ' NV', ' NH', ' NJ', ' NM', ' NY', ' NC',
               ' ND', ' OH', ' OK', ' OR', ' PA', ' RI', ' SC', ' SD', ' TN', ' TX', ' UT',
               ' VT', ' VA', ' WA', ' WV', ' WI', ' WY', ' DC')

# full name and abbreviation
UNIVERSITY_ABBR <- list(
  c('university of california los angeles', 'UCLA', 'UC Los Angeles'),
  c('university of california san diego', 'UCSD', 'UC San Diego'),
  c('california institute of technology', 'caltech'),
  c('city college of new york', 'CCNY'),
  c('carnegie mellon university', 'CMU'),
  c('georgia institute of technology', 'georgia tech'),
  c('pennsylvania state university', 'penn state'),
  c('university of massachusetts amherst', 'UMass'),
  c('city university of new york', ' cuny'),
  c('havard university school of', 'harvard school of')
)

# use to concat university with string
UNIVERSITY_MULTIPLE_CAMPUS <- list(
  c('university of california', 'berkeley', 'los angeles', 'davis', 'davis medical center', 'irvine', 'irvine medical center', 'san francisco', 'santa barbara', 'riverside'),
  c('university of illinois urbana champaign', 'urbana champaign', 'urbana', 'champaign'),
  c('university of illinois', 'urbana champaign', 'chicago', 'springfield', 'peoria'),
  c('university of pittsburgh', 'medical center'),
  c('university of michigan', 'ann arbor', 'dearborn', 'health system', 'flint'),
  c('university of minnesota', 'duluth', 'morris', 'medical Ccnter', 'rochester', 'crookston')
)

  COUNTRY_DOMAIN <- as.data.frame(read.delim("core/textMining/wiki country code top-level domains.txt")[,1:2])
  COUNTRY_DOMAIN$Entity <- tolower(COUNTRY_DOMAIN$Entity)


